import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import Link from "next/link";
import { BrandLockup } from "./components/brand/BrandLockup";
import styles from "./shell.module.css";
import "./globals.css";
import { APPS } from "@/lib/apps";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

const SITE_URL = "https://frozengrape.app";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Frozen Grape — Worth a spot on your screen.",
    template: "%s · Frozen Grape",
  },
  description:
    "Useful tools. Daily rituals. Games you’ll come back to. Explore the apps we’re building at Frozen Grape, an independent studio in Austin.",
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "Frozen Grape Studios",
    title: "Frozen Grape — Worth a spot on your screen.",
    description:
      "Useful tools. Daily rituals. Games you’ll come back to. Independently made in Austin.",
    // Image generated by opengraph-image.tsx from the shared Pip brand artwork.
  },
  twitter: {
    card: "summary_large_image",
    title: "Frozen Grape — Worth a spot on your screen.",
    description:
      "Useful tools. Daily rituals. Games you’ll come back to. Independently made in Austin.",
  },
};

function jsonLd() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": `${SITE_URL}/#org`,
        name: "Frozen Grape Studios",
        url: SITE_URL,
        description: "An independent studio in Austin building useful, playful apps for iPhone.",
        logo: `${SITE_URL}/brand/pip/hello.png`,
      },
      {
        "@type": "ItemList",
        name: "Frozen Grape apps",
        itemListElement: APPS.map((app, i) => ({
          "@type": "ListItem",
          position: i + 1,
          item: {
            "@type": "SoftwareApplication",
            name: app.name,
            applicationCategory: app.category,
            operatingSystem: "iOS",
            offers: { "@type": "Offer", price: app.price === "Free" ? "0" : app.price.replace("$", "") },
            ...(app.appStoreUrl ? { url: app.appStoreUrl } : {}),
          },
        })),
      },
    ],
  };
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${jakarta.variable} antialiased min-h-screen flex flex-col`}>
        <a href="#main" className="skip-link">
          Skip to content
        </a>

        <nav className={styles.navigation} aria-label="Main navigation">
          <Link
            href="/"
            className={styles.brandLink}
            aria-label="Frozen Grape Studios — home"
          >
            <BrandLockup priority />
          </Link>
          <div className={styles.links}>
            <Link href="/#apps" className="hover:text-[var(--ink)] transition-colors">
              Apps
            </Link>
            <Link href="/#studio" className="hover:text-[var(--ink)] transition-colors">
              Studio
            </Link>
            <Link href="/support" className="hover:text-[var(--ink)] transition-colors">
              Support
            </Link>
            <Link href="/contact" className="hover:text-[var(--ink)] transition-colors">
              Contact
            </Link>
          </div>
        </nav>

        <main id="main" className="flex-grow">
          {children}
        </main>

        <footer className="site-footer w-full px-6 py-9 mt-10 text-[13px] text-[var(--muted)]">
          <div className="max-w-5xl mx-auto w-full flex flex-wrap items-center justify-between gap-4">
          <Link href="/" className={styles.brandLink} aria-label="Frozen Grape Studios — home">
            <BrandLockup />
          </Link>
          <div className="flex gap-5">
            <Link href="/#apps" className="hover:text-[var(--ink)] transition-colors">
              Apps
            </Link>
            <Link href="/support" className="hover:text-[var(--ink)] transition-colors">
              Support
            </Link>
            <Link href="/legal" className="hover:text-[var(--ink)] transition-colors">
              Legal
            </Link>
            <Link href="/privacy" className="hover:text-[var(--ink)] transition-colors">
              Privacy
            </Link>
            <Link href="/terms" className="hover:text-[var(--ink)] transition-colors">
              Terms
            </Link>
            <Link href="/contact" className="hover:text-[var(--ink)] transition-colors">
              Contact
            </Link>
          </div>
          <span>© {new Date().getFullYear()} Frozen Grape Studios</span>
          </div>
        </footer>

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd()) }}
        />
      </body>
    </html>
  );
}
